<?php $_product = $this->getProduct(); ?>
<?php
	$increments = 1;
	$productData = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product);
	$qtyIncrements = $productData->getQtyIncrements();
	if($qtyIncrements > 0){
		$increments = $qtyIncrements;
	}
?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
		<label for="qty"><?php echo $this->__('Qty:') ?></label>
        <div class="quantity-decrease" onclick="qtyDown()"><?php echo MAGE::helper('ThemeOptionsBizarre')->getIcon('descreaseqty'); ?></div>
		<input type="text" name="qty" id="qty" maxlength="12" value="<?php if($qtyIncrements > 0){echo $increments;}else{echo $this->getProductDefaultQty() * 1;} ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <div class="quantity-increase" onclick="qtyUp()"><?php echo MAGE::helper('ThemeOptionsBizarre')->getIcon('increaseqty'); ?></div>
		<?php endif; ?>
		
		
		<button type="button" title="<?php echo $buttonTitle ?>" id="product-addtocart-button" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
		
		
        <span id='ajax_loader' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt='' /></span>
		
		
        <?php  echo $this->getChildHtml('', true, true) ?>
        <?php /* 
            <!--div class="ajax_basket_data" style="display:none;">
            <div class="ajax_basket" style="display: block; ">
                <span><?php echo number_format(Mage::getModel('checkout/cart')->getQuote()->getItemsQty(),0); ?></span> IN YOUR SHOPPING CART            </div>
            <div class="ajax_action no-display" style="overflow: block; display: block;"><a href="#">View Shopping Cart</a> | <a href="#">Checkout</a></div>
            </div-->
            <!-- <div class="add-to-link-bss">
                <ul>
                    <li><a href="#">Wishlist</a></li>
                    <li><a href="#">Compare</a></li>
                </ul>
            </div> -->
        */ ?>
        
	<script type="text/javascript">
		function qtyDown(){
			qty_el = document.getElementById('qty');
			qty = qty_el.value;
			if( !isNaN( qty ) && qty > <?php echo $increments; ?> ){
				qty_el.value = parseInt(qty_el.value)-<?php echo $increments; ?>
			}
			return false;
		}
		function qtyUp(){
			qty_el = document.getElementById('qty');
			qty = qty_el.value;
			if( !isNaN( qty )) {
				qty_el.value = parseInt(qty_el.value)+<?php echo $increments; ?>
			}
			return false;
		}

/*		jQuery(document).ready(function(){
    		jQuery("#product-addtocart-button").click(function(){
        		jQuery(".ajax_basket_data").css("display", "block");
        		jQuery(".add-to-box .add-to-cart").css(" width", "500px");
		    });
		});;
*/
    </script>
<?php endif; ?>