<?php

?>
<div class="yotpo bottomLine"
    data-appkey="7OdOiiLcs0sXTwrBODsrhl8KVux3i3rih8uQ59Kq"
    data-product-id="<?php echo $this->getProductId() ?>"
    data-name="<?php echo $this->getProductName() ?>"
    data-url="<?php echo $this->getProductUrl() ?>"   
    data-image-url="<?php echo $this->getProductImageUrl() ?>"
    data-description="<?php echo $this->getProductDescription() ?>">
</div>