<?php $product = Mage::registry('current_product'); ?>
<?php 
	$storeId = Mage::app()->getStore()->getStoreId();
	switch ($storeId) {
	    case 4:
	        $conversionId = 0;
	        break;
	    case 5:
	        $conversionId = 99719369;
	        break;
	    case 6:
	        $conversionId = 1003131220;
	        break;
	    default:
	        $conversionId = 1041527249;
	}
?>


<script type="text/javascript">
var google_tag_params = {
ecomm_prodid: "<?php echo $product->getSku(); ?>",
ecomm_pagetype: "product",
ecomm_totalvalue: <?php echo $product->getFinalPrice(); ?>,
};
</script>
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = <?php echo $conversionId; ?>;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/<?php echo $conversionId; ?>/?guid=ON&amp;script=0"/>
</div>
</noscript>
