<?php

?>
<div class="yotpo bottomLine"
    data-appkey="ug0P7nhPNDt330TX8gDy3yQpqyahJNxyFYdIFaef"
    data-product-id="<?php echo $this->getProductId() ?>"
    data-name="<?php echo $this->getProductName() ?>"
    data-url="<?php echo $this->getProductUrl() ?>"   
    data-image-url="<?php echo $this->getProductImageUrl() ?>"
    data-description="<?php echo $this->getProductDescription() ?>">
</div>